### ISSUE TITLE
離開關卡確認

### ISSUE THREAD

**Issue by sun92122** [sun92122/TypingGame#3]
於暫停頁面退出關卡（包含回主選單及關卡選擇），應有確認頁面

**Comment by xup6rmp4jo3** [comment]
![image](https://github.com/sun92122/TypingGame/assets/103333210/592a7130-a5cc-44f1-88d4-8365640dd82b)
![image](https://github.com/sun92122/TypingGame/assets/103333210/f1a808f3-3e24-4d25-86eb-38cb631f2430)
